### ISSUE TITLE
Broken on TF2 as of 06/21/22 update

### ISSUE THREAD

**Issue by sapphonie** [sapphonie/sourcemod-nativevotes-updated#14]

**Comment by nosoop** [comment]
Disassembly of `CVoteController::CreateVote`'s new `VoteStart` setup:
```
mov     dword ptr [esp+4], offset aVotestart ; "VoteStart"
mov     [esp], eax
call    _Z16UserMessageBeginR16IRecipientFilterPKc ; UserMessageBegin(IRecipientFilter &,char const*)
mov     eax, [edi+370h]
mov     [esp], eax
call    _Z16MessageWriteBytei ; MessageWriteByte(int)
mov     eax, [edi+3B8h]
mov     [esp], eax
call    _Z16MessageWriteLongi ; MessageWriteLong(int)
mov     eax, [edi+3B4h]
mov     [esp], eax
call    _Z16MessageWriteBytei ; MessageWriteByte(int)
mov     eax, [esi]
mov     [esp], esi
call    dword ptr [eax+2Ch]
mov     [esp], eax
call    _Z18MessageWriteStringPKc ; MessageWriteString(char const*)
mov     eax, [esi]
mov     [esp], esi
call    dword ptr [eax+0Ch]
mov     [esp], eax
call    _Z18MessageWriteStringPKc ; MessageWriteString(char const*)
mov     eax, [esi]
mov     [esp], esi
call    dword ptr [eax+44h]
movzx   eax, al
mov     [esp], eax
call    _Z16MessageWriteBoolb ; MessageWriteBool(bool)
mov     eax, [esi+4]
xor     edx, edx
```
There's a new `MessageWriteLong(int)` call in between the team / initiator bytes.

**Comment by sapphonie** [comment]
> 
> There's a new `MessageWriteLong(int)` call in between the team / initiator bytes; it corresponds to `CVoteController::m_nVoteIdx `

You da bes, thanks

**Comment by nosoop** [comment]
Globally initiated votes are fine with the hotfix commits in [my branch](https://github.com/nosoop/sourcemod-nativevotes/commits/multivotes).  I'll throw a PR up for that at some point.

Players cannot use standard keybinds on issues they've created themselves even on unmodded servers; reported in ValveSoftware/Source-1-Games#3934.

**Comment by nosoop** [comment]
Aside for future work:

To support multiple teams, for starters, you'll need to figure out which `vote_controller` entity corresponds to which team.  On the server, this is handled in the `g_voteControllerRed`, `g_voteControllerBlu`, and `g_voteControllerGlobal` globals; I think they're all identical aside from the global they're stored in.
